version: '3.1'
services:
  db:
    image: postgres:9.6-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: helios
      POSTGRES_USER: helios
      POSTGRES_PASSWORD: example
    volumes:
      - /docker/helios-postgres:/var/run/postgresql
    expose:
      - "5432"
    container_name: db

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:8080"
    depends_on:
      - db
    container_name: adminer

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      CELERY_BROKER_URL: 'amqp://rabbitmq'
      DATABASE_URL: 'postgresql://helios:example@db:5432/helios'
      ALLOWED_HOSTS: '*'
      URL_HOST: 'http://vote.zeus.ugent.be/'
      SECURE_URL_HOST: 'https://vote.zeus.ugent.be/'
    depends_on:
      - db
      - rabbitmq
    ports:
      - "127.0.0.1:8001:8000"
    container_name: web

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      CELERY_BROKER_URL: 'amqp://rabbitmq'
    depends_on:
      - db
      - rabbitmq
    container_name: worker

  rabbitmq:
    image: rabbitmq:3.8.3-alpine
    expose: # not needed but more clear
        - "5672"
    container_name: rabbitmq
